# Generated by Django 4.0.2 on 2023-06-01 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='review',
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.book')),
            ],
            options={
                'db_table': 'Review',
            },
        ),
    ]
