# Generated by Django 4.0.2 on 2023-06-01 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_book_review_bookreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='reviewForeign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.bookreview'),
        ),
        migrations.AlterModelTable(
            name='bookreview',
            table=None,
        ),
    ]
