# Generated by Django 4.0.2 on 2023-06-01 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_bookreview_book_book_reviewforeign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='BookForeign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.book'),
        ),
    ]
