# Generated by Django 4.0.2 on 2023-06-01 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_bookreview_bookforeign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='reviewForeign',
            new_name='review',
        ),
    ]
