# Generated by Django 4.0.2 on 2023-06-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_reviewforeign_book_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reviews',
            field=models.TextField(blank=True, null=True),
        ),
    ]
